# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.9'
services:
  hive4-mariadb:
    image: mariadb:10
    container_name: hive4-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=my_mariadb_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    ports:
      - "3307:3306" # Exponer el puerto 3306 para MariaDB
    networks:
      - gestbd_net
    volumes:
      - mariadb-data:/var/lib/mysql
      
  phpmyadmin-maria-hive4:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mariadb-hive4-gestdb
    environment:
      PMA_HOST: hive4-mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: my_password
    restart: always
    ports:
      - "8083:80"  # Puerto para acceder a phpMyAdmin
    depends_on:
      - hive4-mariadb
    networks:
      - gestbd_net
      
  hive4-postgres:
    image: postgres
    restart: unless-stopped
    container_name: hive4-postgres
    hostname: hive4-postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql
    networks:
      - gestbd_net
      
  pgadmin-hive4: # postgres:5432 or localhost:5432 
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - hive4-postgres
    volumes:
      - ./datapga:/tmpdata
      - ./dataexample:/var/lib/pgadmin/storage
    networks:
          - gestbd_net

  metastore:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - hive4-postgres
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive4-postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
        - '9083:9083'
    volumes:
        - ./warehouse:/opt/hive/data/warehouse
        - type: bind
          source: ${POSTGRES_LOCAL_PATH}
          target: /opt/hive/lib/postgres.jar
        - ./drivers/postgresql-42.7.4.jar:/opt/hive/lib/postgresql-42.7.4.jar
        - ./drivers/mariadb-java-client-3.4.1.jar:/opt/hive/lib/mariadb-java-client-3.4.1.jar
    networks:
      - gestbd_net

  hiveserver2:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - ./warehouse:/opt/hive/data/warehouse
      - ./drivers/postgresql-42.7.4.jar:/opt/hive/lib/postgresql-42.7.4.jar
      - ./drivers/mariadb-java-client-3.4.1.jar:/opt/hive/lib/mariadb-java-client-3.4.1.jar
    networks:
      - gestbd_net
      
  hue:
    image: gethue/hue:latest
    container_name: hue
    environment:
      - HUE_DATABASE=sqlite3
      - HUE_SECRET_KEY=password           # hivegesdb:password
      - HUE_HIVE_SERVER_HOST=hiveserver2  # Apuntar a tu servicio de Hive
      - HUE_HIVE_SERVER_PORT=10000        # Puerto del HiveServer2
    ports:
      - "8084:8888"  # El puerto 8084 es para acceder a Hue
    volumes:
      - ./hueconf/hue.ini:/usr/share/hue/desktop/conf/hue.ini
    networks:
      - gestbd_net
    depends_on:
      - metastore

volumes:
  hive-db:
  warehouse:
  mariadb-data:

networks:
  gestbd_net:
    external: true
